package madsdf.shimmer.gui;

import com.google.common.eventbus.EventBus;
import madsdf.shimmer.glview.ShimmerAngleConverter;
import madsdf.shimmer.glview.ShimmerCanvas;
import java.awt.Cursor;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Observer;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.prefs.BackingStoreException;
import java.util.prefs.Preferences;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import madsdf.shimmer.event.Globals;
import org.apache.commons.lang3.StringUtils;
import org.jfree.chart.ChartPanel;

/**
 * This is the main class of the application. The design has been realised with
 * the Netbeans graphic tool.
 *
 * Java version : JDK 1.6.0_21 IDE : Netbeans 7.1.1
 *
 * @author Gregoire Aubert
 * @version 1.0
 */
public class ShimmerMoveAnalyzerFrame extends JFrame {
    private final static String PREFS_DEVICES = "btDevicesIDs";

    private static final long serialVersionUID = 1L;
    private final static Logger Log = Logger.getLogger(ShimmerMoveAnalyzerFrame.class.getName());
    // The bluetooth connected device
    private BluetoothDeviceCom connectedDevice;
    // The class drawing the chart
    private ChartsDrawer chartsDrawer;
    // Controller for OpenGL display
    private ShimmerAngleConverter angleConverter;
    // The write buffer
    private BufferedWriter out;
    // Remember user input
    private Preferences prefs;
    
    // The max commands and samples
    private int maxCommand = 6;
    private int maxSample = 10;
    private int currentCommand = 1;
    private int currentSample = 1;
    
    private final String btid;
    
    private final Logger log = Logger.getLogger(ShimmerMoveAnalyzerFrame.class.getName());
    
    private final EventBus eventBus;

    /**
     * Creates new form ShimmerMoveAnalyzerFrame
     *
     * @param args The numbers of commands and samples can be passed via the
     * console parameters.
     */
    public ShimmerMoveAnalyzerFrame(String title, String btid) {
        this.btid = btid;
        initComponents();
        setTitle(title);
        /*prefs = Preferences.userRoot().node(this.getClass().getName());
        restorePreferences();*/
        chartsDrawer = new ChartsDrawer((ChartPanel) panAccel, (ChartPanel) panGyro);
        
        final ShimmerCanvas shimmerCanvas = (ShimmerCanvas)panGL;
        eventBus = Globals.getBusForShimmer(btid);
        angleConverter = new ShimmerAngleConverter(eventBus, txtLog);
        
        // Eventbus registration
        eventBus.register(shimmerCanvas);
        eventBus.register(chartsDrawer);
        eventBus.register(angleConverter);
        
        txtLog.setEditable(false);
        
        labBtId.setText(btid);
        
        // Automatically start streaming
        // TODO: This is DEBUG only
        connect();
        btnRun.doClick();
    }
    
    /*private void restorePreferences() {
        Log.info(prefs.get(PREFS_DEVICES, ""));
        String[] devices = StringUtils.split(prefs.get(PREFS_DEVICES, ""), ";");
        jcbDevices.setModel(new DefaultComboBoxModel(devices));
    }
    
    private void appendToPreferences(String key, String value) {
        List<String> lst = new ArrayList<String>(Arrays.asList(StringUtils.split(prefs.get(key, ""), ";")));
        lst.add(value);
        
        prefs.put(key, StringUtils.join(lst, ";"));
        try {
            prefs.flush();
        } catch (BackingStoreException ex) {
            Logger.getLogger(ShimmerMoveAnalyzerFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        Log.info("Preferences saved");
    }*/
    
    private void connect() {
        try {
            log.info("Connecting to shimmer...");
            final String btServiceID = "btspp://00066646" + btid + ":1;authenticate=false;encrypt=false;master=false";
            connectedDevice = new BluetoothDeviceCom(eventBus, btid);
            connectedDevice.connect(btServiceID);
            btnLatest.setEnabled(true);
            btnRun.setEnabled(true);
            btnSave.setEnabled(true);
            log.info("Connected to shimmer");
        } catch (IOException ex) {
            Logger.getLogger(ShimmerMoveAnalyzerFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblCmd = new javax.swing.JLabel();
        lblSample = new javax.swing.JLabel();
        btnSave = new java.awt.Button();
        btnLatest = new java.awt.Button();
        btnRun = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        jPanelConnect = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        labBtId = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        panAccel = new ChartPanel(null);
        panGyro = new ChartPanel(null);
        panGL = ShimmerCanvas.createCanvas(this);
        panLog = new javax.swing.JScrollPane();
        txtLog = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Graph accelerometer / gyro");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("shimmer_icon.png")));
        setMinimumSize(new java.awt.Dimension(500, 400));
        setName("frmShimmerMoveAnalyzer"); // NOI18N
        setPreferredSize(new java.awt.Dimension(400, 400));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel7.setText("Current command :");

        jLabel8.setText("Current sample :");

        lblCmd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCmd.setText("1");

        lblSample.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSample.setText("1");

        btnSave.setEnabled(false);
        btnSave.setLabel("Save sample");
        btnSave.setName(""); // NOI18N
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnLatest.setEnabled(false);
        btnLatest.setLabel("Lastest 100");
        btnLatest.setName(""); // NOI18N
        btnLatest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLatestActionPerformed(evt);
            }
        });

        btnRun.setText("Run");
        btnRun.setEnabled(false);
        btnRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRunActionPerformed(evt);
            }
        });

        btnStop.setText("Stop");
        btnStop.setEnabled(false);
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblSample))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(59, 59, 59)
                        .addComponent(lblCmd)))
                .addGap(31, 31, 31)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLatest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 3, Short.MAX_VALUE)
                        .addComponent(btnRun)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnStop)
                        .addGap(1, 1, 1)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(lblCmd))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(lblSample)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRun)
                            .addComponent(btnStop))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLatest, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblCmd.getAccessibleContext().setAccessibleName("lblCmd");
        lblSample.getAccessibleContext().setAccessibleName("lblSample");
        btnLatest.getAccessibleContext().setAccessibleName("btnStop");

        jLabel9.setText("BT ID :");

        labBtId.setText("jLabel1");

        javax.swing.GroupLayout jPanelConnectLayout = new javax.swing.GroupLayout(jPanelConnect);
        jPanelConnect.setLayout(jPanelConnectLayout);
        jPanelConnectLayout.setHorizontalGroup(
            jPanelConnectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConnectLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labBtId)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelConnectLayout.setVerticalGroup(
            jPanelConnectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConnectLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConnectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(labBtId))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel2.setLayout(new java.awt.GridLayout(2, 2, 5, 5));

        panAccel.setName("panAccel"); // NOI18N

        javax.swing.GroupLayout panAccelLayout = new javax.swing.GroupLayout(panAccel);
        panAccel.setLayout(panAccelLayout);
        panAccelLayout.setHorizontalGroup(
            panAccelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 262, Short.MAX_VALUE)
        );
        panAccelLayout.setVerticalGroup(
            panAccelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 193, Short.MAX_VALUE)
        );

        jPanel2.add(panAccel);

        panGyro.setName("panAccel"); // NOI18N

        javax.swing.GroupLayout panGyroLayout = new javax.swing.GroupLayout(panGyro);
        panGyro.setLayout(panGyroLayout);
        panGyroLayout.setHorizontalGroup(
            panGyroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 262, Short.MAX_VALUE)
        );
        panGyroLayout.setVerticalGroup(
            panGyroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 193, Short.MAX_VALUE)
        );

        jPanel2.add(panGyro);

        javax.swing.GroupLayout panGLLayout = new javax.swing.GroupLayout(panGL);
        panGL.setLayout(panGLLayout);
        panGLLayout.setHorizontalGroup(
            panGLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 262, Short.MAX_VALUE)
        );
        panGLLayout.setVerticalGroup(
            panGLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 193, Short.MAX_VALUE)
        );

        jPanel2.add(panGL);

        txtLog.setColumns(20);
        txtLog.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txtLog.setRows(5);
        panLog.setViewportView(txtLog);

        jPanel2.add(panLog);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelConnect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelConnect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   private void btnLatestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLatestActionPerformed
       chartsDrawer.drawLatestHundred();
   }//GEN-LAST:event_btnLatestActionPerformed

   private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
       btnStop.setEnabled(false);
       chartsDrawer.setDrawing(false);
       btnRun.setEnabled(true);
       btnLatest.setEnabled(true);
   }//GEN-LAST:event_btnStopActionPerformed

   private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
       try {

           // Check if the file is already open
           if (out == null) {
               out = new BufferedWriter(new FileWriter("RawData.txt"));
           }

           out.write("COMMAND " + currentCommand + " SAMPLE " + currentSample + "\n");

           // Initialise the string tab
           String[] lignes = new String[6];
           lignes[0] = "Accel X : ";
           lignes[1] = "Accel Y : ";
           lignes[2] = "Accel Z : ";
           lignes[3] = "Gyro X : ";
           lignes[4] = "Gyro Y : ";
           lignes[5] = "Gyro Z : ";

           // Save the last 100 values in the right string
           synchronized (chartsDrawer.getLastHundred()) {
               for (AccelGyro.Sample sample : chartsDrawer.getLastHundred()) {
                   for (int i = 0; i < 3; ++i) {
                       lignes[i] += sample.accel[i] + ";";
                   }
                   for (int i = 0; i < 3; ++i) {
                       lignes[i] += sample.gyro[i] + ";";
                   }
               }
           }

           // Write the file
           for (String ligne : lignes) {
               out.write(ligne.replaceFirst(";$", "\n"));
           }

           // Change the sample or the command
           if (++currentSample > maxSample) {
               currentSample = 1;
               if (++currentCommand > maxCommand) {
                   btnSave.setEnabled(false);
                   out.close();
                   lblCmd.setText("#");
               } else {
                   lblCmd.setText(currentCommand + "");
               }
           }

           lblSample.setText(currentSample + "");
       } catch (IOException ex) {
           System.err.println("ShimmerMoveAnalyserFrame.btnSaveActionPerformed: " + ex);
       }
   }//GEN-LAST:event_btnSaveActionPerformed

   private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       if (connectedDevice != null) {
           connectedDevice.stop();
       }
   }//GEN-LAST:event_formWindowClosing

   private void btnRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRunActionPerformed
       btnRun.setEnabled(false);
       btnLatest.setEnabled(false);
       chartsDrawer.setDrawing(true);
       btnStop.setEnabled(true);
   }//GEN-LAST:event_btnRunActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(final String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            boolean nimbus = false;
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    nimbus = true;
                    break;
                }
            }
            if (!nimbus || System.getProperty("os.name").toLowerCase().indexOf("win") >= 0) {
                javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShimmerMoveAnalyzerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShimmerMoveAnalyzerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShimmerMoveAnalyzerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShimmerMoveAnalyzerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        // TODO: Get that from properties file
        final String btid = "BDCD";
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShimmerMoveAnalyzerFrame("Shimmer", btid).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnLatest;
    private javax.swing.JButton btnRun;
    private java.awt.Button btnSave;
    private javax.swing.JButton btnStop;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelConnect;
    private javax.swing.JLabel labBtId;
    private javax.swing.JLabel lblCmd;
    private javax.swing.JLabel lblSample;
    private javax.swing.JPanel panAccel;
    private javax.swing.JPanel panGL;
    private javax.swing.JPanel panGyro;
    private javax.swing.JScrollPane panLog;
    private javax.swing.JTextArea txtLog;
    // End of variables declaration//GEN-END:variables
}
